# Generated by Django 5.1.6 on 2025-05-06 16:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermoviestatus',
            unique_together={('user', 'movie')},
        ),
        migrations.RemoveField(
            model_name='usermoviestatus',
            name='session_id',
        ),
    ]
