# Generated by Django 5.2 on 2025-05-07 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_usermoviestatus_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorynote',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.movie'),
        ),
    ]
