# Generated by Django 5.1.6 on 2025-05-07 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_memorynote_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorynote',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
    ]
